UT.SL.UI/UT.SL.UI.WebUI/Areas/Admin/Controllers/App_UserInfoController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using UT.SL.Helper;
using UT.SL.UI.WebUI.Controllers;
using UT.SL.Model;
using UT.SL.Data.LINQ;
using UT.SL.DAL;
using System.Web;
using UT.SL.Model.Enumeration;
using UT.SL.BLL;


namespace UT.SL.UI.WebUI.Areas.Admin.Controllers
{

    [Authorize()]
    public class App_UserInfoController : BaseController
    {
        public ActionResult EditUserInfo(Guid Id)
        {
            var formObject = App_UserInfoDAL.Get(Id);
            if (formObject == null)
            {
                formObject = new App_UserInfo { Id = 0, App_User = new App_User { GuidId = Id } };
            }
            var listItems = new SelectListItems
             {
                 Items = TopicDAL.GetAll().OrderBy(x => x.Title).Select(x => new SelectListItem
                 {
                     Value = x.Id.ToString(),
                     Text = x.Title
                 })
             };
            if (formObject.App_User != null && formObject.App_User.UserTopicMappers != null)
            {
                listItems.SelectedIds = formObject.App_User.UserTopicMappers.Select(x => x.TopicId.ToString()).ToArray();
            }
            var model = new FormModel<App_UserInfo, SelectListItems>
            {
                FormObject = formObject,
                ExtraKnownData = listItems
            };
            return PartialView(model);
        }

        [HttpPost()]
        [ValidateAntiForgeryToken()]
        public ActionResult EditUserInfo(FormModel<App_UserInfo, SelectListItems> model)
        {
            var bpr = new BatchProcessResultModel();
            ModelState.Remove("FormObject.App_User.UserName");
            ModelState.Remove("FormObject.App_User.Password");
            if (ModelState.IsValid)
            {
                try
                {
                    var drm = ((DALReturnModel<App_UserInfo>)ManageAction.ProxyCall(ManageAction.RequestDetail(CurrentUser, Request.RequestContext, (int)ObjectType.App_UserInfo),
                               new Func<App_UserInfo, BatchProcessResultModel, DALReturnModel<App_UserInfo>>(App_UserInfoDAL.Update), model.FormObject, bpr));
                    bpr = drm.BPR;
                    var userId = drm.ReturnObject.App_User.Id;
                    if (bpr.Failed > 0)
                    {
                        return PartialView("ProcessResult", bpr);
                    }
                    else
                    {
                        ManageAction.ProxyCall(ManageAction.RequestDetail(CurrentUser, Request.RequestContext, (int)ObjectType.App_User),
                                      new Func<App_User, DALReturnModel<App_User>>(App_UserDAL.DeleteUserTopics), new App_User { Id = userId });
                        if (model.ExtraKnownData != null && model.ExtraKnownData.SelectedIds != null)
                        {
                            foreach (var item in model.ExtraKnownData.SelectedIds)
                            {
                                var tempTopicMapper = new UserTopicMapper
                                {
                                    UserId = userId,
                                    TopicId = Int32.Parse(item)
                                };
                                var drm2 = (DALReturnModel<UserTopicMapper>)ManageAction.ProxyCall(ManageAction.RequestDetail(CurrentUser, Request.RequestContext, (int)ObjectType.UserTopicMapper),
                                      new Func<UserTopicMapper, BatchProcessResultModel, DALReturnModel<UserTopicMapper>>(App_UserDAL.AddUserTopic), tempTopicMapper, bpr);
                                bpr = drm2.BPR;
                            }
                        }
                        bpr.SuccessClientScript = "$('#searchForm').submit();";
                    }
                }
                catch (System.Exception)
                {
                    bpr.AddError(UT.SL.Model.Resource.App_Errors.BprMainUnknownError, true, true);
                }
            }
            else
            {
                bpr.AddModelStateErrors(ModelState);
            }
            return PartialView("ProcessResult", bpr);
        }

    }
}

UT.SL.UI/UT.SL.UI.WebUI/Areas/Admin/Views/App_UserInfo/EditUserInfo.cshtml
@using UT.SL.Helper
@using UT.SL.Security
@model  FormModel<UT.SL.Data.LINQ.App_UserInfo, SelectListItems>
<div class="">
    @using (Ajax.BeginForm("EditUserInfo", "App_UserInfo", new { area = "Admin" }, new AjaxOptions()
{
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "SubmitResultOAI",
    HttpMethod = "POST",
    LoadingElementId = "loadingAjax"
}, new { @class = "form-horizontal" }))
    {
        @Html.AntiForgeryToken()  
        @Html.ValidationSummary(true)    
        <fieldset>
            <legend>@UT.SL.Model.Resource.App_Common.OtherAccountInfo</legend>
            <div class="" id="SubmitResultOAI">
            </div>
            <div class="">
                <div class="form-group">
                    <label class="control-label" for="">@Html.LabelFor(model => model.FormObject.NationalId)</label>
                    <div class="controls">
                        @Html.EditorFor(model => model.FormObject.NationalId)
                    </div>
                    <div class="controls">
                        @Html.ValidationMessageFor(model => model.FormObject.NationalId)
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label" for="">@Html.LabelFor(model => model.FormObject.BirsthDate)</label>
                    <div class="controls">
                        @Html.EditorFor(model => model.FormObject.BirsthDate)
                    </div>
                    <div class="controls">
                        @Html.ValidationMessageFor(model => model.FormObject.BirsthDate)
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label" for="">@Html.LabelFor(model => model.FormObject.BSin)</label>
                    <div class="controls">
                        @Html.EditorFor(model => model.FormObject.BSin)
                    </div>
                    <div class="controls">
                        @Html.ValidationMessageFor(model => model.FormObject.BSin)
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label" for="">@Html.LabelFor(model => model.FormObject.MSin)</label>
                    <div class="controls">
                        @Html.EditorFor(model => model.FormObject.MSin)
                    </div>
                    <div class="controls">
                        @Html.ValidationMessageFor(model => model.FormObject.MSin)
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label" for="">@Html.LabelFor(model => model.FormObject.PHDin)</label>
                    <div class="controls">
                        @Html.EditorFor(model => model.FormObject.PHDin)
                    </div>
                    <div class="controls">
                        @Html.ValidationMessageFor(model => model.FormObject.PHDin)
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label" for="">@Html.LabelFor(model => model.FormObject.Occupation)</label>
                    <div class="controls">
                        @Html.EditorFor(model => model.FormObject.Occupation)
                    </div>
                    <div class="controls">
                        @Html.ValidationMessageFor(model => model.FormObject.Occupation)
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label" for="">@Html.LabelFor(model => model.FormObject.About)</label>
                    <div class="controls">
                        @Html.TextAreaFor(model => model.FormObject.About)
                    </div>
                    <div class="controls">
                        @Html.ValidationMessageFor(model => model.FormObject.About)
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label" for="">@Html.LabelFor(model => model.FormObject.Title)</label>
                    <div class="controls">
                        @Html.DropDownListFor(model => model.FormObject.Title, UT.SL.Model.Enumeration.Utility.GetSelectList(typeof(UT.SL.Model.Enumeration.PersonTitleType), "Select Title"))
                    </div>
                    <div class="controls">
                        @Html.ValidationMessageFor(model => model.FormObject.Title)
                    </div>
                </div>


                <div class="form-group">
                    <label class="control-label" for="">@UT.SL.Model.Resource.App_Common.InterestedIn</label>
                    <div class="controls">
                        @Html.ListBoxFor(model => model.ExtraKnownData.SelectedIds, Model.ExtraKnownData.Items, new { data_multiselectsecond = "true" })
                    </div>
                    <div class="controls">
                    </div>
                </div>
                <div class="form-group">
                    <div class="controls">
                        <input type="submit" value="@(UT.SL.Model.Resource.App_Common.Submit)" id="submit"  class="btn btn-default btn btn-default-default submit"/>
                        <input type="hidden" value="@Model.FormObject.Id" name ="Id"/>
                        @Html.HiddenFor(model => model.FormObject.App_User.GuidId)
                    </div>
                </div>
            </div>
        </fieldset>
    }
    <script>
        $(function () {
            $.InitialComponents();
            initializeUploaderUserPic();
            $("[data-multiselectsecond]").kendoMultiSelect();
        });
    </script>
</div>