UT.SL.UI/UT.SL.UI.WebUI/ViewModels/AssignmentSubmission/GradeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UT.SL.DAL;
using UT.SL.Helper;
using UT.SL.UI.WebUI.Controllers;


namespace ViewModels.AssignmentSubmission
{
    public class GradeViewModel
    {
        public GradeViewModel()
        {
        }

        public GradeViewModel(UT.SL.Data.LINQ.AssignmentSubmission assignmentSubmission,
                                   UT.SL.Data.LINQ.Grade grade
                                    )
        {
            AssignmentSubmission = assignmentSubmission;
            Grade = grade;
        }


        public UT.SL.Data.LINQ.AssignmentSubmission AssignmentSubmission { get; set; }
        public UT.SL.Data.LINQ.Grade Grade { get; set; }
    }
}

UT.SL.UI/UT.SL.UI.WebUI/Areas/Admin/Controllers/GradeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UT.SL.BLL;
using UT.SL.DAL;
using UT.SL.Data.LINQ;
using UT.SL.Helper;
using UT.SL.Model;
using UT.SL.Model.Enumeration;
using UT.SL.UI.WebUI.Controllers;
using ViewModels.AssignmentSubmission;

namespace UT.SL.UI.WebUI.Areas.Admin.Controllers
{
    public class GradeController : BaseController
    {        
        public ActionResult Edit(int Id)
        {
            var model = GradeDAL.Get(Id);
            return PartialView(model);
        }

        [HttpPost()]
        [ValidateAntiForgeryToken()]
        public ActionResult Edit(Grade model)
        {
            var bpr = new BatchProcessResultModel();
            var grade = GradeDAL.Get(model.Id);
            ModelState.Remove("Id");
            if (ModelState.IsValidField(UT.SL.Model.Resource.Grade.GradeValue))
            {
                double gradeChange = 0;
                gradeChange = (double)model.GradeValue - (double)grade.GradeValue;
                if (grade != null)
                {
                    grade.GradeValue = model.GradeValue;
                    grade.CreateDate = DateTime.Now;
                    grade.UserId = CurrentUser.Id;
                }
                try
                {
                    var drm = (DALReturnModel<Grade>)ManageAction.ProxyCall(ManageAction.RequestDetail(CurrentUser, Request.RequestContext, (int)ObjectType.Grade),
                           new Func<Grade, BatchProcessResultModel, bool, DALReturnModel<Grade>>(GradeDAL.Update), grade, bpr, true);
                    bpr = drm.BPR;
                    //update Credit
                    var assignmentSubmission = AssignmentSubmissionDAL.Get(grade.ObjectId.Value);
                    ModelManager.UpdateCreditValue((int)UT.SL.Model.Enumeration.ActionType.Grade, assignmentSubmission.Id, (int)UT.SL.Model.Enumeration.ObjectType.AssignmentSubmission, 0, gradeChange);
                    //update credit
                    if (bpr.Failed > 0)
                    {
                        return PartialView("ProcessResult", bpr);
                    }
                    else
                    {
                        bpr.SuccessClientScript = "$('#searchForm').submit();";
                    }
                }
                catch (System.Exception)
                {
                    bpr.AddError(UT.SL.Model.Resource.App_Errors.BprMainUnknownError, true, true);
                }
            }
            else
            {
                bpr.AddError(string.Format(UT.SL.Model.Resource.App_Errors.Range0To100, UT.SL.Model.Resource.Grade.GradeValue), true, true);
                //bpr.AddModelStateErrors(ModelState);
                return PartialView("ProcessResult", bpr);
            }
            return PartialView("GetOneGrade", grade);

        }

        public ActionResult GetOneGrade(int Id)
        {
            var model = GradeDAL.Get(Id);
            return PartialView(model);
        }

        public ActionResult GradeComponent(int id, int type, int gradeFrom, int grade = -1)
        {
            ViewBag.GradeFrom = gradeFrom;
            ViewBag.CurrentUserName = CurrentUser.UserName;
            var gradeObject = GradeDAL.GetAll(id, type).LastOrDefault();
            var model = new Grade();
            if (gradeObject != null)
            {
                if (grade != -1)
                {
                    if (gradeObject.GradeValue == grade)
                    {
                        ManageAction.ProxyCall(ManageAction.RequestDetail(CurrentUser, Request.RequestContext, (int)ObjectType.Grade),
                                      new Func<Grade, DALReturnModel<Grade>>(GradeDAL.Delete), gradeObject);         
                        //update Credit
                        ModelManager.UpdateCreditValue((int)UT.SL.Model.Enumeration.ActionType.Grade, id, type, 0, -(gradeObject.GradeValue));
                        //update credit
                        model = new Grade
                        {
                            ObjectId = id,
                            ObjectType = type
                        };
                    }
                    else
                    {
                        //update Credit
                        ModelManager.UpdateCreditValue((int)UT.SL.Model.Enumeration.ActionType.Grade, id, type, 0, grade - gradeObject.GradeValue);
                        //update credit
                        gradeObject.GradeValue = grade;
                        gradeObject.UserId = CurrentUser.Id;
                        var bpr = new BatchProcessResultModel();
                        var drm = (DALReturnModel<Grade>)ManageAction.ProxyCall(ManageAction.RequestDetail(CurrentUser, Request.RequestContext, (int)ObjectType.Grade),
                          new Func<Grade, BatchProcessResultModel, bool, DALReturnModel<Grade>>(GradeDAL.Update), gradeObject, bpr, true);
                        bpr = drm.BPR;
                        model = gradeObject;
                    }
                }
                else
                {
                    model = gradeObject;
                }
            }
            else
            {
                if (grade != -1)
                {
                    var sharedObject = ManageObject.GetSharedObject(id, type);
                    var newGrade = new Grade
                       {
                           CreateDate = DateTime.Now,
                           ObjectId = id,
                           ObjectType = type,
                           UserId = CurrentUser.Id,
                           GradeValue = grade
                       };
                    if (sharedObject.CourseId.HasValue)
                        newGrade.CourseId = sharedObject.CourseId.Value;
                    newGrade.ParentObjectId = sharedObject.CameFromId;
                    newGrade.ParentObjectType = sharedObject.CameFromType;
                    if (sharedObject != null)
                    {
                        newGrade.CourseId = newGrade.CourseId > 0 ? newGrade.CourseId : sharedObject.CourseId.Value;
                        if (sharedObject.CreateUser.Id > 0)
                            newGrade.GradeOwnerId = sharedObject.CreateUser.Id;
                    }
                    var bpr = new BatchProcessResultModel();
                    var drm = (DALReturnModel<Grade>)ManageAction.ProxyCall(ManageAction.RequestDetail(CurrentUser, Request.RequestContext, (int)ObjectType.Grade),
                         new Func<Grade, BatchProcessResultModel, DALReturnModel<Grade>>(GradeDAL.Add), newGrade, bpr);
                    bpr = drm.BPR;
                    //update Credit
                    ModelManager.UpdateCreditValue((int)UT.SL.Model.Enumeration.ActionType.Grade, id, type, 0, grade);
                    //update credit
                    model = newGrade;
                }
                else
                {
                    model = new Grade
                    {
                        ObjectId = id,
                        ObjectType = type
                    };
                }
            }
            return PartialView(model);
        }

        public ActionResult GetGradeChart(Guid userId, int courseId)
        {
            var grades = GradeDAL.GetAllUserAndCourse(courseId, App_UserDAL.Get(userId).Id);
            var userIntId = App_UserDAL.Get(userId).Id;
            var allCoursegrades = GradeDAL.GetAllCourse(courseId);
            var courseForums = CourseDAL.Get(courseId).Forums.Where(x => x.IsPublishd && x.IsValid).ToList();
            var courseAssignments = CourseDAL.Get(courseId).Assignments.Where(x => x.IsPublished && x.IsValid).ToList();
            var model = new FormModel<List<GradeTypeModel>, Course>();
            var tempGrades = new List<GradeTypeModel>();
            //int i = 0;
            //foreach (var item in grades)
            //{
            //    i++;
            //    var objectModel = ManageObject.GetSharedObject(item.ObjectId.Value, item.ObjectType.Value);
            //    var tempGrade = new GradeTypeModel
            //    {
            //        CreateDate = item.CreateDate,
            //        MaxGrade = allCoursegrades.Where(x => x.ParentObjectId == item.ParentObjectId && x.ParentObjectType == item.ParentObjectType).Max(x => x.GradeValue),
            //        MinGrade = allCoursegrades.Where(x => x.ParentObjectId == item.ParentObjectId && x.ParentObjectType == item.ParentObjectType).Min(x => x.GradeValue),
            //        MyGrade = item.GradeValue,
            //        Title = ((item.ObjectType == 8) ? UT.SL.Model.Resource.App_Common.FD + i : UT.SL.Model.Resource.App_Common.Assignment + i)
            //    };
            //    if (objectModel != null)
            //    {
            //        var title = objectModel.CameFromTitle;
            //        var titleLong = title;
            //        if (title.Length >= 4)
            //            title = title.Substring(0, 4) + "...";
            //        if (titleLong.Length >= 20)
            //            titleLong = titleLong.Substring(0, 19) + "...";
            //        tempGrade.Title = title;
            //        tempGrade.FullTitle = titleLong;
            //    }
            //    tempGrades.Add(tempGrade);
            //}
            foreach (var forum in courseForums.Where(x => x.ForumDiscussions.Any(p => p.UserId == userIntId)))
            {
                if (grades.Any(x => x.ParentObjectId == forum.Id && x.ParentObjectType == (int)UT.SL.Model.Enumeration.ObjectType.Forum))
                {

UT.SL.UI/UT.SL.UI.WebUI/Areas/Admin/Views/Grade/Edit.cshtml
@using UT.SL.Helper
@using UT.SL.Security
@model UT.SL.Data.LINQ.Grade
@using (Ajax.BeginForm("Edit",
    "Grade",
    new { area = "Admin" },
    new AjaxOptions()
    {
        InsertionMode = InsertionMode.Replace,
        HttpMethod = "POST",
        UpdateTargetId = "SubmitResult",
        //OnSuccess = "'" + Url.Action("GetOneGrade", "Grade", new { area = "admin", Id = Model.Id }) + "';",
        OnSuccess = "'" + Url.Action("GetOneGrade", "Grade", new { area = "admin", Id = Model.Id }) + "';",
        LoadingElementId = "LoadingGifCEResource"
    }, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <div id="SubmitResult">
        <div class="form-group">
            @*<label class="control-label col-sm-3" for="">@Html.LabelFor(model => model.Grade.GradeValue)</label>*@
            <div class="col-sm-12">
                <div class="input-group">
                    @Html.TextBoxFor(model => model.GradeValue, new { @class = "form-control" })
                </div>
                @Html.ValidationMessageFor(model => model.GradeValue)
            </div>
        </div>
        @*@Html.TextBoxFor(model => model.GradeValue, new { @class = "input-small span4" })
        @Html.ValidationMessageFor(model => model.GradeValue)*@
        @* <input type="submit" value="@(UT.SL.Model.Resource.App_Common.Submit)" id="submit" class="btn btn-default submit btn btn-default-primary" />*@
    </div>
}

<script type="text/javascript">
    $(function () {
        $.InitialComponents();
    });
</script>

UT.SL.UI/UT.SL.UI.WebUI/Areas/Admin/Views/Grade/GetGradeChart.cshtml
@model UT.SL.Helper.FormModel<List<UT.SL.Model.GradeTypeModel>, UT.SL.Data.LINQ.Course>
@{
    String categories = string.Empty;
    String dataMin = string.Empty;
    String dataMax = string.Empty;
    String fullTitle = string.Empty;
    String dataMine = string.Empty;
    var i = 1;
    
    foreach (var item in Model.FormObject)
    {
        //categories += "\'" + item.Title + "\', ";
        categories += "\'" + i++ + "\', ";
    }
    if (!string.IsNullOrEmpty(categories))
    {
        categories = categories.Substring(0, categories.LastIndexOf(','));
    }

    foreach (var item in Model.FormObject)
    {
        if (item.MinGrade.HasValue)
        {
            dataMin += "" + item.MinGrade + ", ";
        }
    }
    if (!string.IsNullOrEmpty(dataMin))
    {
        dataMin = dataMin.Substring(0, dataMin.LastIndexOf(','));
    }

    foreach (var item in Model.FormObject)
    {
        if (item.MaxGrade.HasValue)
        {
            dataMax += "" + (item.MaxGrade) + ", ";
        }
    }
    if (!string.IsNullOrEmpty(dataMax))
    {
        dataMax = dataMax.Substring(0, dataMax.LastIndexOf(','));
    }

    foreach (var item in Model.FormObject)
    {
        fullTitle += "\'" + (item.FullTitle) + "\', ";
    }
    if (!string.IsNullOrEmpty(fullTitle))
    {
        fullTitle = fullTitle.Substring(0, fullTitle.LastIndexOf(','));
    }

    foreach (var item in Model.FormObject)
    {
        if (item.MyGradeDouble.HasValue)
        {
            dataMine += "" + item.MyGradeDouble + ", ";
        }
    }
    if (!string.IsNullOrEmpty(dataMine))
    {
        dataMine = dataMine.Substring(0, dataMine.LastIndexOf(','));
    }

}

<script type="text/javascript">
    var fullTitlesGrade = [@Html.Raw(fullTitle)];
    $(function () {
        $('#gradecontainer').highcharts({

            chart: {
                type: 'column'
            },

            title: {
                text: '@(UT.SL.Model.Resource.App_Common.Grades) @(Model.ExtraKnownData.Title)'
            },

            xAxis: {
                categories: [@Html.Raw(categories)],
                title: {
                    text: '@UT.SL.Model.Resource.App_Common.GradedMaterials'
                }
            },

            yAxis: {
                min: 0,
                title: {
                    text: '@UT.SL.Model.Resource.App_Common.Grade'
                }
            },

            tooltip: {
                formatter: function () {
                    var result = '<span style="font-size:10px">' + fullTitlesGrade[this.points[0].point.x] + '</span><table>';
                    $.each(this.points, function (i, data) {
                        result += '<tr><td style="color:' + data.series.color + ';padding:0">' + data.series.name + ': </td>' +
                                      '<td style="padding:0"><b>' + data.y + '</b></td></tr>';
                    });
                    result += '</table>';
                    return result;
                },
                shared: true,
                useHTML: true
            },

            plotOptions: {
                column: {
                    pointPadding: 0.2,
                    borderWidth: 0
                },
                series: {
                    cursor: 'pointer',
                    point: {
                        events: {
                            click: function () {
                                $.ajax({
                                    url: "@(Url.Action("GetGradeDetails", "Grade", new { area = "Admin", userId = ViewBag.UserId }))&courseId=@(ViewBag.CourseId)&position=" + this.x,
                                    beforeSend: function () {
                                        $('#loadingAjax').show();
                                    },
                                    success: function (html) {
                                        if (html) {
                                            $("#gradeDetail").html(html);
                                        }
                                    },
                                    complete: function () {
                                        $('#loadingAjax').hide();
                                    }
                                });
                            }
                        }
                    }
                }
            },

            series: [{
                name: '@UT.SL.Model.Resource.App_Common.MaxGrade',
                data: [@Html.Raw(dataMax)]
            }, {
                name: '@UT.SL.Model.Resource.App_Common.YourGrade',
                data: [@Html.Raw(dataMine)]
            }, {
                name: '@UT.SL.Model.Resource.App_Common.MinGrade',
                data: [@Html.Raw(dataMin)]
            }]
        });
    });
</script>
<h3>@UT.SL.Model.Resource.App_Common.Grades</h3>
<h5>Hint: Grade 0 means your item has not been graded yet.</h5>
<div id="gradecontainer" style="margin: 0 auto">@UT.SL.Model.Resource.App_Common.Loading</div>

UT.SL.UI/UT.SL.UI.WebUI/Areas/Admin/Views/Grade/GetOneGrade.cshtml
@using UT.SL.Helper
@using UT.SL.Security
@model UT.SL.Data.LINQ.Grade

@Html.Label(@Model.GradeValue.ToString())


UT.SL.UI/UT.SL.UI.WebUI/Areas/Admin/Views/Grade/GetProgressChart - Copy.cshtml
@model UT.SL.Helper.FormModel<List<UT.SL.Model.ProgressModel>, UT.SL.Data.LINQ.Course>
@{
    String categories = string.Empty;
    String dataTopic = string.Empty;
    String dataMine = string.Empty;
    double wholeAverage = 0;
    double myAverage = 0;

    foreach (var item in Model.FormObject)
    {
        categories += "\'" + item.Title + "\', ";
    }
    categories = categories.Substring(0, categories.LastIndexOf(','));

    foreach (var item in Model.FormObject)
    {
        dataTopic += "" + item.TopicValue + ", ";
        wholeAverage += item.TopicValue;
    }
    dataTopic = dataTopic.Substring(0, dataTopic.LastIndexOf(','));

    foreach (var item in Model.FormObject)
    {
        dataMine += "" + (item.MyValue) + ", ";
        myAverage += item.MyValue;
    }
    dataMine = dataMine.Substring(0, dataMine.LastIndexOf(','));

    wholeAverage = wholeAverage / Model.FormObject.Count();
    myAverage = myAverage / Model.FormObject.Count();

}

<script type="text/javascript">

    var myTopics = [@Html.Raw(categories)];

    $(function () {
        $('#progresscontainer').highcharts({
            chart: {
                polar: true
            },

            title: {
                text: '@(Model.ExtraKnownData.Title)'
            },

            pane: {
                startAngle: 0,
                endAngle: 360
            },

            xAxis: {
                tickInterval: @(360 / Model.FormObject.Count()),
                min: 0,
                max: 360,
                labels: {
                    formatter: function () {
                        return myTopics[1];
                        console.log(this);
                    }
                }

            },

            yAxis: {
                min: 0
            },

            plotOptions: {
                series: {
                    pointStart: 0,
                    pointInterval: @(360 / Model.FormObject.Count())
                    },
                column: {
                    pointPadding: 0,
                    groupPadding: 0
                }
            },

            @if (wholeAverage >= myAverage)
            {
                 @:colors: ['#4572A7', '#FF4500', '#228B22'] ,
                        }
            else
            {
                 @:colors: ['#4572A7', '#228B22', '#228B22'] ,
                        }

            series: [{
                type: 'column',
                name: '@UT.SL.Model.Resource.App_Common.Topics',
                data: [@Html.Raw(dataTopic)],
                pointPlacement: 'between'
            }, {
                type: 'line',
                name: '@UT.SL.Model.Resource.App_Common.MyProgress',
                data: [@Html.Raw(dataMine)]
            }]
        });
    });
</script>
<h3>@UT.SL.Model.Resource.App_Common.Progress</h3>
<div id="progresscontainer" style="margin: 0 auto">@UT.SL.Model.Resource.App_Common.Loading</div>

UT.SL.UI/UT.SL.UI.WebUI/Areas/Admin/Views/Grade/GetUserKnowledgeProfileChart.cshtml
@model UT.SL.Helper.FormModel<List<UT.SL.Model.GradeTypeModel>, UT.SL.Data.LINQ.Course>
@{
    String categories = string.Empty;
    String dataMin = string.Empty;
    String dataMax = string.Empty;
    String fullTitle = string.Empty;
    String dataMine = string.Empty;

    foreach (var item in Model.FormObject)
    {
        categories += "\'" + item.Title + "\', ";
    }
    if (!string.IsNullOrEmpty(categories))
    {
        categories = categories.Substring(0, categories.LastIndexOf(','));
    }

    foreach (var item in Model.FormObject)
    {
        if (item.MinGrade.HasValue)
        {
            dataMin += "" + item.MinGrade + ", ";
        }
    }
    if (!string.IsNullOrEmpty(dataMin))
    {
        dataMin = dataMin.Substring(0, dataMin.LastIndexOf(','));
    }

    foreach (var item in Model.FormObject)
    {
        if (item.MaxGrade.HasValue)
        {
            dataMax += "" + (item.MaxGrade) + ", ";
        }
    }
    if (!string.IsNullOrEmpty(dataMax))
    {
        dataMax = dataMax.Substring(0, dataMax.LastIndexOf(','));
    }

    foreach (var item in Model.FormObject)
    {
        fullTitle += "\'" + (item.FullTitle) + "\', ";
    }
    if (!string.IsNullOrEmpty(fullTitle))
    {
        fullTitle = fullTitle.Substring(0, fullTitle.LastIndexOf(','));
    }

    foreach (var item in Model.FormObject)
    {
        if (item.MyGradeDouble.HasValue)
        {
            dataMine += "" + item.MyGradeDouble + ", ";
        }
    }
    if (!string.IsNullOrEmpty(dataMine))
    {
        dataMine = dataMine.Substring(0, dataMine.LastIndexOf(','));
    }

}

<script type="text/javascript">
    var fullTitlesK = [@Html.Raw(fullTitle)];

    $(function () {
        $('#userKnowledgeProfile').highcharts({

            chart: {
                type: 'column'
            },

            title: {
                text: '@(UT.SL.Model.Resource.App_Common.UserKnowledgeProfile) @(Model.ExtraKnownData.Title)'
            },

            xAxis: {
                categories: [@Html.Raw(categories)],
                title: {
                    text: '@UT.SL.Model.Resource.App_Common.Topics'
                }
            },

            yAxis: {
                min: 0,
                title: {
                    text: '@UT.SL.Model.Resource.App_Common.Knowledge'
                }
            },

            tooltip: {
                formatter: function () {
                    var result = '<span style="font-size:10px">' + fullTitlesK[this.points[0].point.x] + '</span><table>';
                    $.each(this.points, function (i, data) {
                        result += '<tr><td style="color:' + data.series.color + ';padding:0">' + data.series.name + ': </td>' +
                                      '<td style="padding:0"><b>' + data.y + '</b></td></tr>';
                    });
                    result += '</table>';
                    return result;
                },
                shared: true,
                useHTML: true
            },

            plotOptions: {
                column: {
                    pointPadding: 0.2,
                    borderWidth: 0
                },
                series: {
                    cursor: 'pointer',
                    point: {
                        events: {
                            click: function () {
                                $.ajax({
                                    url: "@(Url.Action("KnowledgeDetails", "Grade", new { area = "Admin", userId = ViewBag.UserId }))&courseId=@(ViewBag.CourseId)&position=" + this.x,
                                    beforeSend: function () {
                                        $('#loadingAjax').show();
                                    },
                                    success: function (html) {
                                        if (html) {
                                            $("#knowledgeDetail").html(html);
                                        }
                                    },
                                    complete: function () {
                                        $('#loadingAjax').hide();
                                    }
                                });
                            }
                        }
                    }
                }
            },

            series: [{
                name: '@UT.SL.Model.Resource.App_Common.UserKnowledgeProfileMAX',
                data: [@Html.Raw(dataMax)]
            }, {
                name: '@UT.SL.Model.Resource.App_Common.MyKnowledgeProfile',
                data: [@Html.Raw(dataMine)]
            }, {
                name: '@UT.SL.Model.Resource.App_Common.UserKnowledgeProfileMIN',
                data: [@Html.Raw(dataMin)]
            }]
        });
    });
</script>
<h3>@UT.SL.Model.Resource.App_Common.UserKnowledgeProfile</h3>
<div id="userKnowledgeProfile" style="margin: 0 auto">@UT.SL.Model.Resource.App_Common.Loading</div>

UT.SL.UI/UT.SL.UI.WebUI/Areas/Admin/Views/Grade/GetUserSoActProfileChart.cshtml
@model UT.SL.Helper.FormModel<List<UT.SL.Model.GradeTypeModel>, UT.SL.Data.LINQ.Course>
@{
    String categories = string.Empty;
    String dataMin = string.Empty;
    String dataMax = string.Empty;
    String fullTitle = string.Empty;
    String dataMine = string.Empty;

    foreach (var item in Model.FormObject)
    {
        categories += "\'" + item.Title + "\', ";
    }
    if (!string.IsNullOrEmpty(categories))
    {
        categories = categories.Substring(0, categories.LastIndexOf(','));
    }

    foreach (var item in Model.FormObject)
    {
        if (item.MinGrade.HasValue)
        {
            dataMin += "" + item.MinGrade + ", ";
        }
    }
    if (!string.IsNullOrEmpty(dataMin))
    {
        dataMin = dataMin.Substring(0, dataMin.LastIndexOf(','));
    }

    foreach (var item in Model.FormObject)
    {
        if (item.MaxGrade.HasValue)
        {
            dataMax += "" + (item.MaxGrade) + ", ";
        }
    }
    if (!string.IsNullOrEmpty(dataMax))
    {
        dataMax = dataMax.Substring(0, dataMax.LastIndexOf(','));
    }

    foreach (var item in Model.FormObject)
    {
        fullTitle += "\'" + (item.FullTitle) + "\', ";
    }
    if (!string.IsNullOrEmpty(fullTitle))
    {
        fullTitle = fullTitle.Substring(0, fullTitle.LastIndexOf(','));
    }

    foreach (var item in Model.FormObject)
    {
        if (item.MyGradeDouble.HasValue)
        {
            dataMine += "" + item.MyGradeDouble + ", ";
        }
    }
    if (!string.IsNullOrEmpty(dataMine))
    {
        dataMine = dataMine.Substring(0, dataMine.LastIndexOf(','));
    }

}

<script type="text/javascript">
    var fullTitlesC = [@Html.Raw(fullTitle)];
    $(function () {
        $('#userSoActProfile').highcharts({
            chart: {
                type: 'column'
            },

            title: {
                text: '@(UT.SL.Model.Resource.App_Common.UserSoActProfile) @(Model.ExtraKnownData.Title)'
            },

            xAxis: {
                categories: [@Html.Raw(categories)],
                title: {
                    text: '@UT.SL.Model.Resource.App_Common.Topics'
                }
            },

            yAxis: {
                min: 0,
                title: {
                    text: '@UT.SL.Model.Resource.App_Common.SoActValue'
                }
            },

            tooltip: {
                formatter: function () {
                    var result = '<span style="font-size:10px">' + fullTitlesC[this.points[0].point.x] + '</span><table>';
                    $.each(this.points, function (i, data) {
                        result += '<tr><td style="color:' + data.series.color + ';padding:0">' + data.series.name + ': </td>' +
                                      '<td style="padding:0"><b>' + data.y +'</b></td></tr>';
                    });
                    result += '</table>';
                    return result;
                },
                shared: true,
                useHTML: true
            },

            plotOptions: {
                column: {
                    pointPadding: 0.2,
                    borderWidth: 0
                },
                series: {
                    cursor: 'pointer',
                    point: {
                        events: {
                            click: function () {
                                $.ajax({
                                    url: "@(Url.Action("GetSoActDetails", "Grade", new { area = "Admin", userId = ViewBag.UserId }))&courseId=@(ViewBag.CourseId)&position=" + this.x,
                                    beforeSend: function () {
                                        $('#loadingAjax').show();
                                    },
                                    success: function (html) {
                                        if (html) {
                                            $("#soActDetail").html(html);
                                        }
                                    },
                                    complete: function () {
                                        $('#loadingAjax').hide();
                                    }
                                });
                            }
                        }
                    }
                }
            },

            series: [{
                name: '@UT.SL.Model.Resource.App_Common.UserSoActProfileMAX',
                data: [@Html.Raw(dataMax)]
            }, {
                name: '@UT.SL.Model.Resource.App_Common.MySoActProfile',
                data: [@Html.Raw(dataMine)]
            }, {
                name: '@UT.SL.Model.Resource.App_Common.UserSoActProfileMIN',
                data: [@Html.Raw(dataMin)]
            }]
        });
    });
</script>
<h3>@UT.SL.Model.Resource.App_Common.UserSoActProfile</h3>
<div id="userSoActProfile" style="margin: 0 auto">@UT.SL.Model.Resource.App_Common.Loading</div>