UT.SL.UI/UT.SL.UI.WebUI/Controllers/MyHomeController.cs
/*
 * ****************************************************************
 * Filename:        MyHomeController.cs 
 * version:         
 * Author's name:   Fatemeh Orooji, Pezhman Nasirifardfard, Elearning lab 
 * Creation date:   
 * Purpose:         containig Actions used in user homepage body
 * ****************************************************************
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UT.SL.BLL;
using UT.SL.DAL;
using UT.SL.Data.LINQ;
using UT.SL.Helper;
using UT.SL.Model;
using UT.SL.Model.Enumeration;
using UT.SL.UI.WebUI.Areas.Admin.Controllers;

namespace UT.SL.UI.WebUI.Controllers
{
    /// <summary>
    /// contains actions used to provide user home page body elements such as post
    /// </summary>
    [Authorize]
    public class MyHomeController : BaseController
    {

        public ActionResult Index(int? rank, string filter)
        {
            if (rank.HasValue)
                ViewBag.LinkRank = rank.Value;
            if (!String.IsNullOrEmpty(filter))
            {
                ViewBag.Filter = filter;
            }
            return View();
        }

        public ActionResult GetPanel(string filter)
        {
            ViewBag.Filter = filter;
            return PartialView();
        }

        public ActionResult PostResource()
        {
            var model = new FormModel<Resource, List<SelectListItems>>();
            model.FormObject = new Resource();
            model.ExtraKnownData = new List<SelectListItems>();
            var tempItems = new List<SelectListItem>();
            tempItems = new List<SelectListItem>();
            tempItems.Add(new SelectListItem
            {
                Text = UT.SL.Model.Resource.App_Common.All,
                Value = "D_1"
            });
            tempItems.AddRange(CurrentUser.SocialGroups.Where(x => x.GroupMembers.Any(p => p.UserId == CurrentUser.Id && p.IsCircleAdmin.Value == 1)).Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.Title
            }).ToList());
            model.ExtraKnownData.Add(new SelectListItems
            {
                Items = tempItems,
                SelectedIds = new string[] { "D_1" }
            });
            ViewBag.UserId = CurrentUser.Id;
            return PartialView(model);
        }

        public ActionResult SaveResource(HttpPostedFileBase resourceFile, int? id, int? overwite)
        {
            int fileId = 0;
            try
            {
                if (resourceFile != null)
                {
                    if (overwite.HasValue && id.HasValue)
                    {
                        var bpr = new BatchProcessResultModel();
                        var resource = ResourceDAL.Get(id.Value);
                        resource.FileMime = resourceFile.ContentType;
                        resource.FileSize = resourceFile.ContentLength;
                        resource.FileTitle = resourceFile.FileName;
                        byte[] tempFile = null;
                        tempFile = new byte[resourceFile.ContentLength];
                        resourceFile.InputStream.Read(tempFile, 0, resourceFile.ContentLength);
                        resource.FileContent = tempFile;
                        var drm = (DALReturnModel<Resource>)ManageAction.ProxyCall(ManageAction.RequestDetail(CurrentUser, Request.RequestContext, (int)ObjectType.Resource),
                                       new Func<Resource, BatchProcessResultModel, DALReturnModel<Resource>>(ResourceDAL.UpdateFile), resource, bpr);
                        bpr = drm.BPR;
                    }
                    else
                    {
                        var newFile = new Resource
                        {
                            CreateDate = DateTime.Now,
                            FileMime = resourceFile.ContentType,
                            FileSize = resourceFile.ContentLength,
                            FileTitle = resourceFile.FileName,
                            GuidId = Guid.NewGuid(),
                            IsValid = false,
                            IsPublishd = false,
                            CreateUserId = CurrentUser.Id,
                            CourseId = null
                        };

                        byte[] tempFile = null;
                        tempFile = new byte[resourceFile.ContentLength];
                        resourceFile.InputStream.Read(tempFile, 0, resourceFile.ContentLength);
                        newFile.FileContent = tempFile;

                        var bpr = new BatchProcessResultModel();
                        var drm = (DALReturnModel<Resource>)ManageAction.ProxyCall(ManageAction.RequestDetail(CurrentUser, Request.RequestContext, (int)ObjectType.Resource),
                            new Func<Resource, BatchProcessResultModel, DALReturnModel<Resource>>(ResourceDAL.Add), newFile, bpr);
                        bpr = drm.BPR;
                        fileId = drm.ReturnObject.Id;
                        if (bpr.Failed > 0)
                        {
                            return Content("0");
                        }
                    }
                }
            }
            catch
            {
                return Content("0");
            }
            return Content(fileId.ToString());
        }

        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult RemoveResource(int id)
        {
            try
            {
                ManageAction.ProxyCall(ManageAction.RequestDetail(CurrentUser, Request.RequestContext, (int)ObjectType.Resource),
                                       new Func<Resource, DALReturnModel<Resource>>(ResourceDAL.Delete), new Resource { Id = id });
            }
            catch
            {
                return Content("0");
            }
            return Content("2");
        }

        public ActionResult DeleteResourceFile(int id)
        {
            try
            {
                ManageAction.ProxyCall(ManageAction.RequestDetail(CurrentUser, Request.RequestContext, (int)ObjectType.Resource),
                                      new Func<Resource, DALReturnModel<Resource>>(ResourceDAL.DeleteFile), new Resource { Id = id });
            }
            catch
            {
                return Content("0");
            }
            return Content("2");
        }

        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult PostResource(FormModel<Resource, List<SelectListItems>> model, string[] groupIds)
        {
            int resourceId = 0;
            try
            {
                if (groupIds == null)
                {
                    return Content("-1");
                }
                var bpr = new BatchProcessResultModel();
                if (model.FormObject.Id > 0)
                {
                    var obj = ResourceDAL.Get(model.FormObject.Id);
                    if (obj != null)
                    {
                        obj.Body = model.FormObject.Body.StringNormalizer();
                        obj.IsValid = true;
                        obj.IsPublishd = true;
                        resourceId = obj.Id;
                        var drm = (DALReturnModel<Resource>)ManageAction.ProxyCall(ManageAction.RequestDetail(CurrentUser, Request.RequestContext, (int)ObjectType.Resource),
                                       new Func<Resource, BatchProcessResultModel, DALReturnModel<Resource>>(ResourceDAL.Update), obj, bpr);
                        bpr = drm.BPR;
                    }
                    else
                    {
                        if (!string.IsNullOrEmpty(model.FormObject.Body.StringNormalizer()))
                        {
                            obj = new Resource
                            {
                                Body = model.FormObject.Body.StringNormalizer(),
                                CourseId = null,
                                CreateDate = DateTime.Now,
                                CreateUserId = CurrentUser.Id,
                                GuidId = Guid.NewGuid(),
                                IsPublishd = true,
                                IsValid = true
                            };
                            var drm = ((DALReturnModel<Resource>)ManageAction.ProxyCall(ManageAction.RequestDetail(CurrentUser, Request.RequestContext, (int)ObjectType.Resource), new Func<Resource, BatchProcessResultModel, DALReturnModel<Resource>>(ResourceDAL.Add), obj, bpr));
                            resourceId = drm.ReturnObject.Id;
                            bpr = drm.BPR;
                        }
                    }
                }
                else
                {
                    if (!string.IsNullOrEmpty(model.FormObject.Body.StringNormalizer()))
                    {
                        var obj = new Resource
                        {
                            Body = model.FormObject.Body.StringNormalizer(),
                            CourseId = null,
                            CreateDate = DateTime.Now,
                            CreateUserId = CurrentUser.Id,
                            GuidId = Guid.NewGuid(),
                            IsPublishd = true,
                            IsValid = true
                        };
                        var drm = ((DALReturnModel<Resource>)ManageAction.ProxyCall(ManageAction.RequestDetail(CurrentUser, Request.RequestContext, (int)ObjectType.Resource), new Func<Resource, BatchProcessResultModel, DALReturnModel<Resource>>(ResourceDAL.Add), obj, bpr));
                        resourceId = drm.ReturnObject.Id;

UT.SL.UI/UT.SL.UI.WebUI/Views/MyHome/EditResource.cshtml
@using UT.SL.Helper
@using UT.SL.Security
@model FormModel<UT.SL.Data.LINQ.Resource, List<SelectListItems>>

<div class="FivePxPadding">
    @using (Ajax.BeginForm("EditResource", new { }, new AjaxOptions()
{
    InsertionMode = InsertionMode.Replace,
    HttpMethod = "POST",
    LoadingElementId = "loadingAjax",
    OnSuccess = "closeEditSection('objectItem" + (int)UT.SL.Model.Enumeration.ObjectType.Resource + Model.FormObject.Id + "', '" + @Url.Action("GetOneObjectAfterEdit", "MyHome", new { area = "", id = Model.FormObject.Id, type = (int)UT.SL.Model.Enumeration.ObjectType.Resource }) + "')"
}, new { data_dom = "editForm" + Model.FormObject.Id, @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <div class="form-group">
            <div class="col-md-offset-1 col-sm-11">
                @Html.TextAreaFor(model => model.FormObject.Body, new { @class = "form-control", placeholder = UT.SL.Model.Resource.App_Common.EnterTitleHere })
            </div>
        </div>
        <div class="form-group hiddenFileUpload alignCul">
            <label class="control-label col-sm-1">@UT.SL.Model.Resource.App_Common.Attach</label>
            <div class="col-sm-11">
                <input name="resourceFile" id="resourceFile" type="file" data-kendouploader="true"
                       data-saveurl="@(Url.Action("SaveResource", "MyHome", new { area = "", id = Model.FormObject.Id, overwite = 1 }))"
                       data-deleteurl="@(Url.Action("DeleteFile", "MyHome", new { area = "" , id = Model.FormObject.Id }))" data-updateid="dummy" />
            </div>
        </div>
        if (Model.FormObject.FileContent != null)
        {
            @Html.Action("FileContentPreviewForDelete", "FileAnnotation", new { area = "Admin", objectId = Model.FormObject.Id, type = (int)UT.SL.Model.Enumeration.ObjectType.Resource })
        }
        <div class="form-group hiddenShareOption alignCul">
            <label class="control-label col-sm-1">@UT.SL.Model.Resource.App_Common.To</label>
            <div class="col-sm-11">
                @HelperUtils.CustomListBoxFor(Model.ExtraKnownData.Last().SelectedIds, Model.ExtraKnownData.Last().Items, "groupIds", null)
            </div>
        </div>
        <div class="row alignCul">
            <div class="col-md-11 col-md-offset-1">
                <button class="btn btn-primary btn-sm submit" title="@UT.SL.Model.Resource.App_Common.Submit"><span class=" glyphicon glyphicon-ok"></span></button>
                <button class="btn btn-default btn-sm closeEditSection " data-cellid="objectItem@((int)UT.SL.Model.Enumeration.ObjectType.Resource)@(Model.FormObject.Id)" data-updateurl="@Url.Action("GetOneObjectAfterEdit", "MyHome", new { area = "", id = Model.FormObject.Id, type = (int)UT.SL.Model.Enumeration.ObjectType.Resource })" title="@UT.SL.Model.Resource.App_Common.Close"><span class=" glyphicon glyphicon-remove"></span></button>
                @Html.HiddenFor(model => model.FormObject.Id)
            </div>
        </div>
    }
    <script type="text/javascript">
        $(function () {
            initializeUploaderWithDon('editForm@(Model.FormObject.Id)');
        });
    </script>
</div>

UT.SL.UI/UT.SL.UI.WebUI/Views/MyHome/GetPanel.cshtml
@{
    var filter = string.Empty;
    if (ViewBag.Filter != null)
    {
        filter = ViewBag.Filter;
    }
}
@if (!String.IsNullOrEmpty(filter))
{
    if (filter == "3")
    {
    @Html.Action("ManageSocialGroupsPanel", "SocialGroup", new { area = "Admin" })
    }
    else if (filter.StartsWith("3_"))
    { 
    @Html.Action("ManageOneSocialGroupsPanel", "SocialGroup", new { area = "Admin", id = filter })
    }
}
else
{
   @Html.Action("SocialGroupsReviewPanel", "SocialGroup", new { area = "Admin" })
}

UT.SL.UI/UT.SL.UI.WebUI/Views/MyHome/Index.cshtml
@{
    ViewBag.Title = UT.SL.Model.Resource.App_Common.MyHome;
}
@section scripts{
    <script type="text/javascript" src="@Url.Content("~/scripts/loader.js")"></script>
    <script type="text/javascript">
        $(function () {
            window.loadUrl = "@(Url.Action("GetObjects", "MyHome", new { area = "", date = DateTime.Now }))";
            window.loadUrlForNewPosts = "@(Url.Action("GetNewObjects", "MyHome", new { area = "" }))"
            window.filterss = '@(ViewBag.Filter != null ? ViewBag.Filter : string.Empty)';
            window.lastCheckDate = '@(DateTime.Now)';
            highLight(@((int)UT.SL.Model.Enumeration.MenuType.MyHome), 0, false, true);
        });
    </script>
}
@section TopLinks{
    @Html.Action("TopMenuLinks", "Home", new { area = "", menuType = (int)UT.SL.Model.Enumeration.MenuType.MyHome, rank = (ViewBag.LinkRank != null ? (int)ViewBag.LinkRank : 0) })
}
<div class="">
    <div class="row">
        <div class="col-md-6" id="mainPortal">
            @*@Html.Action("PostToCourse", new { Model })*@
            @Html.Partial("PostPanel")
        </div>
        <div class="col-md-6 panelCompo" id="stufftobemoved">
            @Html.Action("GetPanel", new { Model, filter = ViewBag.Filter })
        </div>
    </div>
    @*<div class="row" id="hiddenRow" style="display: none; margin-top: -10px">
        <div class="col-md-6">
        </div>
        <div class="col-md-6" id="stufftobemovedhere">
        </div>
    </div>*@
    <div class="row">
        <div class="col-md-12">
            <div id="postswrapper">
                @Html.Action("GetObjects", new { resourceSelections = ViewBag.Filter != null ? ViewBag.Filter : string.Empty })
            </div>
        </div>
    </div>
    <div id="noMorePosts" class="row" style="display:none">
        <div class="col-md-12">
            <div class="feedDiv centerOne boldAndLarger marginBottom20" style="width:100%">
                <span>
                    @UT.SL.Model.Resource.App_Common.NoMorePosts
                </span>
            </div>
        </div>
    </div>
</div>

UT.SL.UI/UT.SL.UI.WebUI/Views/MyHome/ObjectViewer.cshtml
@model UT.SL.Model.ObjectViewModel
    @if (Model.Type == (int)UT.SL.Model.Enumeration.ObjectType.Resource)
    {
        @Html.Partial("ResourceViewer", Model)
    }
    else if (Model.Type == (int)UT.SL.Model.Enumeration.ObjectType.Assignment)
    {
        @Html.Action("AssignmentViewer", "Assignment", new { area = "Admin", id = Model.Id })
    }
    else if (Model.Type == (int)UT.SL.Model.Enumeration.ObjectType.Forum)
    {
        @Html.Action("ForumViewer", "Forum", new { area = "Admin", id = Model.Id })
    }

UT.SL.UI/UT.SL.UI.WebUI/Views/MyHome/PostPanel.cshtml
<div class="postToCourse"> 
    <div id="postTemplate">
        <div class="whatsup"  data-show="postResourceTemplate" data-hide="postTemplate" data-toggleclass="mainPortal" data-showit="true">
        </div>
        <div class="alignCul">
            <div class="resourceIconPost"  data-show="postResourceTemplate" data-hide="postTemplate" data-toggleclass="mainPortal" data-showit="true">
                <div>
                    <span class="glyphicon glyphicon-file"></span>
                </div>
                @UT.SL.Model.Resource.App_Common.ToShare
            </div>           
        </div>
    </div>
    <div id="postResourceTemplate" style="display:none">
        @Html.Action("PostResource")
    </div>     
</div>

UT.SL.UI/UT.SL.UI.WebUI/Views/MyHome/PostResource.cshtml
@using UT.SL.Helper
@using UT.SL.Security
@model FormModel<UT.SL.Data.LINQ.Resource, List<SelectListItems>>
<div class="parentDiv">

    @using (Ajax.BeginForm("PostResource", new { }, new AjaxOptions()
{
    InsertionMode = InsertionMode.Replace,
    HttpMethod = "POST",
    LoadingElementId = "loadingAjax",
    OnSuccess = "updateHomeResource"
}, new { data_dom = "postUserResourceForm", @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <div class="form-group">
            <div class="col-sm-1">@Html.Action("GetUserPic", "App_User", new { area = "admin", Id = ViewBag.UserId, type = (int)UT.SL.Model.Enumeration.ImageSizeType.Large })</div>
            <div class="col-sm-11">
                @Html.TextAreaFor(model => model.FormObject.Body, new { @class = "form-control", placeholder = UT.SL.Model.Resource.App_Common.WhatIsYourMind })
                @Html.ValidationMessageFor(model => model.FormObject.Body)
            </div>
        </div>
        <div class="form-group hiddenFileUpload alignCul">
            <label class="control-label col-sm-1">@UT.SL.Model.Resource.App_Common.Attach</label>
            <div class="col-sm-11">
                <input name="resourceFile" id="resourceFile" type="file" data-kendouploader="true" data-saveurl="@(Url.Action("SaveResource", "MyHome", new { area = "" }))" data-deleteurl="@(Url.Action("RemoveResource", "MyHome", new { area = "" }))" data-updateid="resourceId" />
            </div>
        </div>
        <div class="form-group hiddenShareOption alignCul">
            <label class="control-label col-sm-1">@UT.SL.Model.Resource.App_Common.To</label>
            <div class="col-sm-11">
                @HelperUtils.CustomListBoxFor(Model.ExtraKnownData.Last().SelectedIds, Model.ExtraKnownData.Last().Items, "groupIds", UT.SL.Model.Resource.App_Common.ChooseLearningGroups)
            </div>
        </div>
        <div class="form-group alignCul">
            <div class="col-md-offset-1 col-md-11">
                <div class="">
                    <button class="btn btn-primary submit" type="submit" id="coursePostSubmit" data-hidekendoupload="true">@UT.SL.Model.Resource.App_Common.Submit</button>
                    <div class="btn btn-default cancelClick deleteFileOnCancel" data-show="postTemplate" data-hide="postResourceTemplate" data-toggleclass="mainPortal" data-hideit="true"> @UT.SL.Model.Resource.App_Common.Cancel</div>
                </div>
                <input name="FormObject.Id" id="resourceId" type="hidden" data-resetonpost="true" value="" />
                <input id="resourceUpdateUrl" type="hidden" value="@Url.Action("GetOneResource", "MyHome", new { area = "" })" />
            </div>
        </div>
    }
    @using (Html.BeginForm(null, null, FormMethod.Post, new { data_antiforgery = "true" }))
    {
        @Html.AntiForgeryToken()
    }

</div>
<script type="text/javascript">
    $(function () {
        initializeUploaderWithDon('postUserResourceForm');
    });
</script>

UT.SL.UI/UT.SL.UI.WebUI/Views/MyHome/Resources.cshtml
@using UT.SL.Helper
@using UT.SL.Security
@model List<UT.SL.Model.ObjectViewModelList>

@if (Model.Any())
{
    foreach (var item in Model)
    {
        if (item.IsWide)
        {
            <div class="row">
                <div class="col-md-12">
                    <div id="objectItem@(item.ObjectViewModels.First().Type)@(item.ObjectViewModels.First().Id)">
                        @Html.Partial("ObjectViewer", item.ObjectViewModels.First())
                    </div>
                </div>
            </div>
        }
        else
        {
            if (item.ObjectViewModels.Any())
            {
                <div class="row">
                    <div class="col-md-6 ">
                        @for (int cnt = 0; cnt < item.ObjectViewModels.Count; cnt++)
                        {
                            if (cnt % 2 == 0)
                            {
                                <div id="objectItem@(item.ObjectViewModels[cnt].Type)@(item.ObjectViewModels[cnt].Id)">
                                    @Html.Partial("ObjectViewer", item.ObjectViewModels[cnt])
                                </div>
                            }
                        }
                    </div>
                    <div class="col-md-6">
                        @for (int cnt = 0; cnt < item.ObjectViewModels.Count; cnt++)
                        {
                            if (cnt % 2 == 1)
                            {
                                <div id="objectItem@(item.ObjectViewModels[cnt].Type)@(item.ObjectViewModels[cnt].Id)">
                                    @Html.Partial("ObjectViewer", item.ObjectViewModels[cnt])
                                </div>
                            }
                        }
                    </div>
                </div>
            }
        }
    }
}
@if (ViewBag.LastCheckDate != null)
{
    <script type="text/javascript">
        $(function () {
            window.lastCheckDate = '@(ViewBag.LastCheckDate)';
        });
    </script>
}

UT.SL.UI/UT.SL.UI.WebUI/Views/MyHome/ResourcesCompact.cshtml
@using UT.SL.Helper
@using UT.SL.Security
@using UT.SL.Security
@model List<UT.SL.Model.ObjectViewModelList>
@foreach (var ObjectModel in Model)
{
    foreach (var item in ObjectModel.ObjectViewModels)
    { 
    @Html.Partial("ObjectViewer", item)    
    }
}
@if (ViewBag.LastCheckDate != null)
{ 
    <script type="text/javascript">
        $(function () {
            window.lastCheckDate = '@(ViewBag.LastCheckDate)';
        });
    </script>
}